/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OsobaType struct {
	AdmiIdnoBydl int64 `json:"admiIdnoBydl,omitempty"`
	AdmiIdnoPrby int64 `json:"admiIdnoPrby,omitempty"`
	CcobIdnoBydl int64 `json:"ccobIdnoBydl,omitempty"`
	CcobIdnoPrby int64 `json:"ccobIdnoPrby,omitempty"`
	CisloOboru string `json:"cisloOboru,omitempty"`
	CisloPasu string `json:"cisloPasu,omitempty"`
	CisloUlice string `json:"cisloUlice,omitempty"`
	DatumNaroz string `json:"datumNaroz,omitempty"`
	Email string `json:"email,omitempty"`
	Identifikator string `json:"identifikator,omitempty"`
	Izo string `json:"izo,omitempty"`
	Jmeno string `json:"jmeno,omitempty"`
	MaturitaDatum string `json:"maturitaDatum,omitempty"`
	MistoNar string `json:"mistoNar,omitempty"`
	Mobil string `json:"mobil,omitempty"`
	ObcPrukaz string `json:"obcPrukaz,omitempty"`
	ObcanstviKvalifikace string `json:"obcanstviKvalifikace,omitempty"`
	ObecCizi string `json:"obecCizi,omitempty"`
	ObecIdnoBydl int64 `json:"obecIdnoBydl,omitempty"`
	ObecIdnoPrby int64 `json:"obecIdnoPrby,omitempty"`
	Odkud string `json:"odkud,omitempty"`
	OkresCizi string `json:"okresCizi,omitempty"`
	OkresIdnoBydl int64 `json:"okresIdnoBydl,omitempty"`
	OkresIdnoPrby int64 `json:"okresIdnoPrby,omitempty"`
	OsobIdno int64 `json:"osobIdno,omitempty"`
	Pohlavi string `json:"pohlavi,omitempty"`
	PostaCizi string `json:"postaCizi,omitempty"`
	Poznamka string `json:"poznamka,omitempty"`
	Poznamka2 string `json:"poznamka2,omitempty"`
	PrCisloUlice string `json:"prCisloUlice,omitempty"`
	PrObecCizi string `json:"prObecCizi,omitempty"`
	PrOkresCizi string `json:"prOkresCizi,omitempty"`
	PrPostaCizi string `json:"prPostaCizi,omitempty"`
	PrPscCizi string `json:"prPscCizi,omitempty"`
	PrUlice string `json:"prUlice,omitempty"`
	Prijmeni string `json:"prijmeni,omitempty"`
	PscBydl string `json:"pscBydl,omitempty"`
	PscCizi string `json:"pscCizi,omitempty"`
	PscPrby string `json:"pscPrby,omitempty"`
	RodCislo string `json:"rodCislo,omitempty"`
	RodnePrijmeni string `json:"rodnePrijmeni,omitempty"`
	StatIdnoBydl int64 `json:"statIdnoBydl,omitempty"`
	StatIdnoNaro int64 `json:"statIdnoNaro,omitempty"`
	StatIdnoObca int64 `json:"statIdnoObca,omitempty"`
	StatIdnoPrby int64 `json:"statIdnoPrby,omitempty"`
	StatIdnoStredSkola int64 `json:"statIdnoStredSkola,omitempty"`
	Stav string `json:"stav,omitempty"`
	StredSkolaCizi string `json:"stredSkolaCizi,omitempty"`
	StredSkolaCiziMisto string `json:"stredSkolaCiziMisto,omitempty"`
	StredSkolaCiziObor string `json:"stredSkolaCiziObor,omitempty"`
	Telefon string `json:"telefon,omitempty"`
	TitulPred string `json:"titulPred,omitempty"`
	TitulZa string `json:"titulZa,omitempty"`
	TrvalyPobyt string `json:"trvalyPobyt,omitempty"`
	UcetAdresa string `json:"ucetAdresa,omitempty"`
	UcetBanka string `json:"ucetBanka,omitempty"`
	UcetEuroAdresa string `json:"ucetEuroAdresa,omitempty"`
	UcetEuroBanka string `json:"ucetEuroBanka,omitempty"`
	UcetEuroIban string `json:"ucetEuroIban,omitempty"`
	UcetEuroMajitel string `json:"ucetEuroMajitel,omitempty"`
	UcetEuroMena string `json:"ucetEuroMena,omitempty"`
	UcetEuroPred string `json:"ucetEuroPred,omitempty"`
	UcetEuroZa string `json:"ucetEuroZa,omitempty"`
	UcetIban string `json:"ucetIban,omitempty"`
	UcetMajitel string `json:"ucetMajitel,omitempty"`
	UcetMena string `json:"ucetMena,omitempty"`
	UcetPred string `json:"ucetPred,omitempty"`
	UcetZa string `json:"ucetZa,omitempty"`
	Ulice string `json:"ulice,omitempty"`
	OsobniCisla string `json:"osobniCisla,omitempty"`
	OkresIdnoBydlNazev string `json:"okresIdnoBydlNazev,omitempty"`
	OkresIdnoPrbyNazev string `json:"okresIdnoPrbyNazev,omitempty"`
	ObecIdnoBydlNazev string `json:"obecIdnoBydlNazev,omitempty"`
	ObecIdnoPrbyNazev string `json:"obecIdnoPrbyNazev,omitempty"`
	CcobIdnoBydlNazev string `json:"ccobIdnoBydlNazev,omitempty"`
	CcobIdnoPrbyNazev string `json:"ccobIdnoPrbyNazev,omitempty"`
	StatIdnoBydlNazev string `json:"statIdnoBydlNazev,omitempty"`
	StatIdnoPrbyNazev string `json:"statIdnoPrbyNazev,omitempty"`
}
