/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetUznanyJednorazovym struct {
	JednorazovyPredmet *PredmetStudenta `json:"jednorazovyPredmet,omitempty"`
	Kredity float64 `json:"kredity"`
	PracZkr string `json:"pracZkr,omitempty"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
}
