/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetAkreditaceSeznamZmenType struct {
	DatumPosledniAkred string `json:"datumPosledniAkred,omitempty"`
	Fakulta string `json:"fakulta,omitempty"`
	PracZkr string `json:"pracZkr,omitempty"`
	SeznamZmen string `json:"seznamZmen,omitempty"`
	StavAkreditace string `json:"stavAkreditace,omitempty"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
}
