/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StudentVRoce struct {
	KombIdno int64 `json:"kombIdno,omitempty"`
	KredituNutnoZiskat int32 `json:"kredituNutnoZiskat"`
	KredityAbsolvovaneNormalniPredmetCelkem float64 `json:"kredityAbsolvovaneNormalniPredmetCelkem"`
	KredityUznaneCelkem float64 `json:"kredityUznaneCelkem"`
	KredityZbyvaAbsolvovat float64 `json:"kredityZbyvaAbsolvovat"`
	KredityZiskaneCelkem float64 `json:"kredityZiskaneCelkem"`
	LimitKredituRok int32 `json:"limitKredituRok,omitempty"`
	MistoVyuky int64 `json:"mistoVyuky,omitempty"`
	Obory []StudentNaOboruVRoce `json:"obory,omitempty"`
	Rocnik int32 `json:"rocnik"`
	RokPlatnosti string `json:"rokPlatnosti,omitempty"`
	SkupinaPredz string `json:"skupinaPredz,omitempty"`
}
