/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetStudenta struct {
	JinyPocetKredituNezOdPredmetu bool `json:"jinyPocetKredituNezOdPredmetu"`
	Kredity float64 `json:"kredity"`
	OborIdno int64 `json:"oborIdno"`
	Odlozeno bool `json:"odlozeno"`
	PracZkr string `json:"pracZkr,omitempty"`
	PraveStudovan bool `json:"praveStudovan"`
	PredmetVarianta *PredmetVarianta `json:"predmetVarianta,omitempty"`
	PredmetyUznane []PredmetUznanyJednorazovym `json:"predmetyUznane,omitempty"`
	Rocnik int32 `json:"rocnik"`
	RokPlatnosti string `json:"rokPlatnosti,omitempty"`
	RokVarianty string `json:"rokVarianty,omitempty"`
	Semestr string `json:"semestr,omitempty"`
	Statnice bool `json:"statnice"`
	Statut string `json:"statut,omitempty"`
	StavAbsolvovani string `json:"stavAbsolvovani,omitempty"`
	StplIdno int64 `json:"stplIdno"`
	TypPredmetu string `json:"typPredmetu,omitempty"`
	UspesneAbsolvovany bool `json:"uspesneAbsolvovany"`
	Uznano bool `json:"uznano"`
	ZapsanProPristiRok bool `json:"zapsanProPristiRok"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
	ZnamkaDatum *LocalDate `json:"znamkaDatum,omitempty"`
	ZnamkaHodnoceni string `json:"znamkaHodnoceni,omitempty"`
	ZnamkaPokus int32 `json:"znamkaPokus,omitempty"`
}
