/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkupinaSegmentu struct {
	OrIdno int64 `json:"orIdno,omitempty"`
	Segmenty []Segment `json:"segmenty,omitempty"`
	SumaMinAKreditu int32 `json:"sumaMinAKreditu"`
	SumaMinAPredmetu int32 `json:"sumaMinAPredmetu"`
	SumaMinBKreditu int32 `json:"sumaMinBKreditu"`
	SumaMinBPredmetu int32 `json:"sumaMinBPredmetu"`
}
