/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OborQramInfoType struct {
	OborIdno int64 `json:"oborIdno"`
	NazevCZ string `json:"nazevCZ"`
	NazevEN string `json:"nazevEN"`
	CisloOboru string `json:"cisloOboru"`
	CisloSpecializace string `json:"cisloSpecializace"`
	KodIsced string `json:"kodIsced,omitempty"`
	Zkratka string `json:"zkratka,omitempty"`
	GarantujiciKatedra string `json:"garantujiciKatedra,omitempty"`
	GarantOboruUcitIdno int64 `json:"garantOboruUcitIdno,omitempty"`
	GarantOboruCeleJmeno string `json:"garantOboruCeleJmeno,omitempty"`
	FakultaOboru string `json:"fakultaOboru,omitempty"`
	Typ string `json:"typ"`
	Forma string `json:"forma"`
	Jazyk string `json:"jazyk"`
	Fakulta string `json:"fakulta"`
	KodProgramu string `json:"kodProgramu,omitempty"`
	AnotaceCZ string `json:"anotaceCZ,omitempty"`
	AnotaceEN string `json:"anotaceEN,omitempty"`
	ProfesniProfilyAbsolventuCZ string `json:"profesniProfilyAbsolventuCZ,omitempty"`
	ProfesniProfilyAbsolventuEN string `json:"profesniProfilyAbsolventuEN,omitempty"`
	KvalifikacniPozadavkyCZ string `json:"kvalifikacniPozadavkyCZ,omitempty"`
	KvalifikacniPozadavkyEN string `json:"kvalifikacniPozadavkyEN,omitempty"`
	PredpokladyZnalostiCZ string `json:"predpokladyZnalostiCZ,omitempty"`
	PredpokladyZnalostiEN string `json:"predpokladyZnalostiEN,omitempty"`
	VystupyZnalostiCZ string `json:"vystupyZnalostiCZ,omitempty"`
	VystupyZnalostiEN string `json:"vystupyZnalostiEN,omitempty"`
	PredpokladyDovednostiCZ string `json:"predpokladyDovednostiCZ,omitempty"`
	PredpokladyDovednostiEN string `json:"predpokladyDovednostiEN,omitempty"`
	VystupyDovednostiCZ string `json:"vystupyDovednostiCZ,omitempty"`
	VystupyDovednostiEN string `json:"vystupyDovednostiEN,omitempty"`
	PredpokladyZpusobilostiCZ string `json:"predpokladyZpusobilostiCZ,omitempty"`
	PredpokladyZpusobilostiEN string `json:"predpokladyZpusobilostiEN,omitempty"`
	VystupyZpusobilostiCZ string `json:"vystupyZpusobilostiCZ,omitempty"`
	VystupyZpusobilostiEN string `json:"vystupyZpusobilostiEN,omitempty"`
	OblastVzdelavaniCZ string `json:"oblastVzdelavaniCZ,omitempty"`
	OblastVzdelavaniEN string `json:"oblastVzdelavaniEN,omitempty"`
	VyucMetodyZnalostiCZ string `json:"vyucMetodyZnalostiCZ,omitempty"`
	VyucMetodyZnalostiEN string `json:"vyucMetodyZnalostiEN,omitempty"`
	VyucMetodyDovednostiCZ string `json:"vyucMetodyDovednostiCZ,omitempty"`
	VyucMetodyDovednostiEN string `json:"vyucMetodyDovednostiEN,omitempty"`
	VyucMetodyZpusobilostiCZ string `json:"vyucMetodyZpusobilostiCZ,omitempty"`
	VyucMetodyZpusobilostiEN string `json:"vyucMetodyZpusobilostiEN,omitempty"`
	HodMetodyZnalostiCZ string `json:"hodMetodyZnalostiCZ,omitempty"`
	HodMetodyZnalostiEN string `json:"hodMetodyZnalostiEN,omitempty"`
	HodMetodyDovednostiCZ string `json:"hodMetodyDovednostiCZ,omitempty"`
	HodMetodyDovednostiEN string `json:"hodMetodyDovednostiEN,omitempty"`
	HodMetodyZpusobilostiCZ string `json:"hodMetodyZpusobilostiCZ,omitempty"`
	HodMetodyZpusobilostiEN string `json:"hodMetodyZpusobilostiEN,omitempty"`
	PozadavkyNaPrijetiCZ string `json:"pozadavkyNaPrijetiCZ,omitempty"`
	PozadavkyNaPrijetiEN string `json:"pozadavkyNaPrijetiEN,omitempty"`
	PozadavkyNaPrijetiURL string `json:"pozadavkyNaPrijetiURL,omitempty"`
	PocetPrijimanych string `json:"pocetPrijimanych,omitempty"`
	PocetPrijimanychPoznamka string `json:"pocetPrijimanychPoznamka,omitempty"`
	PozadovanaZdrZpusobilostCZ string `json:"pozadovanaZdrZpusobilostCZ,omitempty"`
	PozadovanaZdrZpusobilostEN string `json:"pozadovanaZdrZpusobilostEN,omitempty"`
	ProfilProgramuCZ string `json:"profilProgramuCZ,omitempty"`
	ProfilProgramuEN string `json:"profilProgramuEN,omitempty"`
	VzdelavaciCileOboruCZ string `json:"vzdelavaciCileOboruCZ,omitempty"`
	VzdelavaciCileOboruEN string `json:"vzdelavaciCileOboruEN,omitempty"`
	ProfilAbsolventaCZ string `json:"profilAbsolventaCZ,omitempty"`
	ProfilAbsolventaEN string `json:"profilAbsolventaEN,omitempty"`
	PredpokladUplatnitelnostiCZ string `json:"predpokladUplatnitelnostiCZ,omitempty"`
	PredpokladUplatnitelnostiEN string `json:"predpokladUplatnitelnostiEN,omitempty"`
	RegulovanePovolaniCZ string `json:"regulovanePovolaniCZ,omitempty"`
	RegulovanePovolaniEN string `json:"regulovanePovolaniEN,omitempty"`
	RegulovanePovolaniUznavaciO string `json:"regulovanePovolaniUznavaciO,omitempty"`
	MoznePracovniPoziceCZ string `json:"moznePracovniPoziceCZ,omitempty"`
	MoznePracovniPoziceEN string `json:"moznePracovniPoziceEN,omitempty"`
	PoznamkaVerejna string `json:"poznamkaVerejna,omitempty"`
	AkreditaceCislo string `json:"akreditaceCislo,omitempty"`
	AkreditaceOd string `json:"akreditaceOd,omitempty"`
	AkreditaceDo string `json:"akreditaceDo,omitempty"`
	AkreditovanoPodleZakona string `json:"akreditovanoPodleZakona,omitempty"`
	TiskSpecializaceDiplomDs string `json:"tiskSpecializaceDiplomDs,omitempty"`
}
