/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AkceType struct {
	RoakIdno int64 `json:"roakIdno,omitempty"`
	Nazev string `json:"nazev,omitempty"`
	Katedra string `json:"katedra,omitempty"`
	Predmet string `json:"predmet,omitempty"`
	Statut string `json:"statut,omitempty"`
	UcitIdno int64 `json:"ucitIdno,omitempty"`
	Ucitel *UcitelRozvrhoveAkceType `json:"ucitel,omitempty"`
	Rok string `json:"rok,omitempty"`
	Budova string `json:"budova,omitempty"`
	Mistnost string `json:"mistnost,omitempty"`
	KapacitaMistnosti int32 `json:"kapacitaMistnosti,omitempty"`
	PlanObsazeni int32 `json:"planObsazeni,omitempty"`
	Obsazeni int32 `json:"obsazeni,omitempty"`
	TypAkce string `json:"typAkce,omitempty"`
	TypAkceZkr string `json:"typAkceZkr,omitempty"`
	Semestr string `json:"semestr,omitempty"`
	Platnost string `json:"platnost,omitempty"`
	Den string `json:"den,omitempty"`
	DenZkr string `json:"denZkr,omitempty"`
	VyucJazyk string `json:"vyucJazyk,omitempty"`
	HodinaOd int32 `json:"hodinaOd,omitempty"`
	HodinaDo int32 `json:"hodinaDo,omitempty"`
	PocetVyucHodin int32 `json:"pocetVyucHodin,omitempty"`
	HodinaSkutOd string `json:"hodinaSkutOd,omitempty"`
	HodinaSkutDo string `json:"hodinaSkutDo,omitempty"`
	TydenOd int32 `json:"tydenOd,omitempty"`
	TydenDo int32 `json:"tydenDo,omitempty"`
	Tyden string `json:"tyden,omitempty"`
	TydenZkr string `json:"tydenZkr,omitempty"`
	GrupIdno int64 `json:"grupIdno,omitempty"`
	JeNadrazena string `json:"jeNadrazena,omitempty"`
	MaNadrazenou string `json:"maNadrazenou,omitempty"`
	Kontakt string `json:"kontakt,omitempty"`
	Krouzky string `json:"krouzky,omitempty"`
	CasovaRada string `json:"casovaRada,omitempty"`
	Datum string `json:"datum,omitempty"`
	DatumOd string `json:"datumOd,omitempty"`
	DatumDo string `json:"datumDo,omitempty"`
	DruhAkce string `json:"druhAkce,omitempty"`
	VsichniUciteleUcitIdno string `json:"vsichniUciteleUcitIdno,omitempty"`
	VsichniUciteleJmenaTituly string `json:"vsichniUciteleJmenaTituly,omitempty"`
	VsichniUciteleJmenaTitulySPodily string `json:"vsichniUciteleJmenaTitulySPodily,omitempty"`
	VsichniUcitelePrijmeni string `json:"vsichniUcitelePrijmeni,omitempty"`
	ReferencedIdno int64 `json:"referencedIdno,omitempty"`
	PoznamkaRozvrhare string `json:"poznamkaRozvrhare,omitempty"`
	NekonaSe string `json:"nekonaSe,omitempty"`
	Owner string `json:"owner,omitempty"`
	ZakazaneAkce string `json:"zakazaneAkce,omitempty"`
}
