/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetAkreditaceType struct {
	Crd string `json:"crd,omitempty"`
	CrdAkred string `json:"crdAkred,omitempty"`
	CzNazev string `json:"czNazev,omitempty"`
	CzNazevAkred string `json:"czNazevAkred,omitempty"`
	DatumPosledniAkred string `json:"datumPosledniAkred,omitempty"`
	ExportColorsInfo string `json:"exportColorsInfo,omitempty"`
	Fakulta string `json:"fakulta,omitempty"`
	Garanti string `json:"garanti,omitempty"`
	GarantiAkred string `json:"garantiAkred,omitempty"`
	HodZaSemKombForma string `json:"hodZaSemKombForma,omitempty"`
	HodZaSemKombFormaAkred string `json:"hodZaSemKombFormaAkred,omitempty"`
	JednotekCv string `json:"jednotekCv,omitempty"`
	JednotekCvAkred string `json:"jednotekCvAkred,omitempty"`
	JednotekPr string `json:"jednotekPr,omitempty"`
	JednotekPrAkred string `json:"jednotekPrAkred,omitempty"`
	JednotekSem string `json:"jednotekSem,omitempty"`
	JednotekSemAkred string `json:"jednotekSemAkred,omitempty"`
	JednotkaCv string `json:"jednotkaCv,omitempty"`
	JednotkaCvAkred string `json:"jednotkaCvAkred,omitempty"`
	JednotkaPr string `json:"jednotkaPr,omitempty"`
	JednotkaPrAkred string `json:"jednotkaPrAkred,omitempty"`
	JednotkaSem string `json:"jednotkaSem,omitempty"`
	JednotkaSemAkred string `json:"jednotkaSemAkred,omitempty"`
	PracZkr string `json:"pracZkr,omitempty"`
	StavAkreditace string `json:"stavAkreditace,omitempty"`
	TypZk string `json:"typZk,omitempty"`
	TypZkAkred string `json:"typZkAkred,omitempty"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
}
