/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StagUserType struct {
	UserName string `json:"userName,omitempty"`
	Role string `json:"role,omitempty"`
	RoleNazev string `json:"roleNazev,omitempty"`
	Fakulta string `json:"fakulta,omitempty"`
	Katedra string `json:"katedra,omitempty"`
	UcitIdno int64 `json:"ucitIdno,omitempty"`
	OsCislo string `json:"osCislo,omitempty"`
	Email string `json:"email,omitempty"`
}
