/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PracovisteType struct {
	Level string `json:"level,omitempty"`
	CisloPracoviste string `json:"cisloPracoviste"`
	Zkratka string `json:"zkratka"`
	Nazev string `json:"nazev,omitempty"`
	AnNazev string `json:"anNazev,omitempty"`
	NadrazenePracoviste string `json:"nadrazenePracoviste,omitempty"`
	TypPracoviste string `json:"typPracoviste,omitempty"`
	TypPracovisteTxt string `json:"typPracovisteTxt,omitempty"`
	CisloPracovisteInterni string `json:"cisloPracovisteInterni,omitempty"`
	Identifikator string `json:"identifikator,omitempty"`
	PlatnostOd string `json:"platnostOd,omitempty"`
	PlatnostDo string `json:"platnostDo,omitempty"`
	TypVedouciho string `json:"typVedouciho,omitempty"`
	TypVedoucihoTxt string `json:"typVedoucihoTxt,omitempty"`
	VedouciUcitIdno int64 `json:"vedouciUcitIdno,omitempty"`
	VedouciJmeno string `json:"vedouciJmeno,omitempty"`
	VedouciPrijmeni string `json:"vedouciPrijmeni,omitempty"`
}
