/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlanInfoType struct {
	StplIdno int64 `json:"stplIdno"`
	OborIdno int64 `json:"oborIdno"`
	Nazev string `json:"nazev"`
	Kreditne string `json:"kreditne,omitempty"`
	LimitKreditu int32 `json:"limitKreditu,omitempty"`
	Etapa int32 `json:"etapa,omitempty"`
	PocetSemestru int32 `json:"pocetSemestru,omitempty"`
	RokPlatnosti string `json:"rokPlatnosti"`
	Verze string `json:"verze"`
	Poznamka string `json:"poznamka,omitempty"`
	Specializace string `json:"specializace,omitempty"`
	VyucJazyk string `json:"vyucJazyk,omitempty"`
	Poradi int32 `json:"poradi,omitempty"`
	EctsZobrazit string `json:"ectsZobrazit,omitempty"`
}
