/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetUciteleType struct {
	Zkratka string `json:"zkratka"`
	Nazev string `json:"nazev"`
	Katedra string `json:"katedra"`
	Rok string `json:"rok"`
	Garant string `json:"garant,omitempty"`
	GarantPodil int32 `json:"garantPodil,omitempty"`
	Prednasejici string `json:"prednasejici,omitempty"`
	PrednasejiciPodil int32 `json:"prednasejiciPodil,omitempty"`
	Cvicici string `json:"cvicici,omitempty"`
	CviciciPodil int32 `json:"cviciciPodil,omitempty"`
	Seminarici string `json:"seminarici,omitempty"`
	SeminariciPodil int32 `json:"seminariciPodil,omitempty"`
	Examinator string `json:"examinator,omitempty"`
}
