/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetPodLimitType struct {
	Fakulta string `json:"fakulta"`
	Katedra string `json:"katedra"`
	Zkratka string `json:"zkratka"`
	RokVarianty string `json:"rokVarianty"`
	SemestrVyuky string `json:"semestrVyuky,omitempty"`
	Nazev string `json:"nazev"`
	StanoveneMinimum int32 `json:"stanoveneMinimum,omitempty"`
	ZapsanychStudentu int32 `json:"zapsanychStudentu,omitempty"`
}
