/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WsCiselnikItemForEditType struct {
	Domena string `json:"domena"`
	Key string `json:"key,omitempty"`
	ValueCs string `json:"valueCs"`
	Zkratka string `json:"zkratka,omitempty"`
	ValueEn string `json:"valueEn,omitempty"`
}
