/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetBlokuType struct {
	Zkratka string `json:"zkratka"`
	Katedra string `json:"katedra"`
	Nazev string `json:"nazev"`
	Kreditu int32 `json:"kreditu"`
	Rok string `json:"rok"`
	DoporucenyRocnik int32 `json:"doporucenyRocnik,omitempty"`
	DoporucenySemestr string `json:"doporucenySemestr,omitempty"`
	VyznamPredmetu string `json:"vyznamPredmetu,omitempty"`
	VyukaLS string `json:"vyukaLS"`
	VyukaZS string `json:"vyukaZS"`
	Rozsah string `json:"rozsah"`
	TypZk string `json:"typZk"`
}
