/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlokInfoType struct {
	BlokIdno int64 `json:"blokIdno"`
	SespIdno int64 `json:"sespIdno,omitempty"`
	Nazev string `json:"nazev"`
	Statut string `json:"statut"`
	MinKred int32 `json:"minKred,omitempty"`
	MaxKred int32 `json:"maxKred,omitempty"`
	MinPocetPredmetu int32 `json:"minPocetPredmetu,omitempty"`
	Poznamka string `json:"poznamka,omitempty"`
	RokPlatnosti string `json:"rokPlatnosti"`
}
