/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrganizaceInfoType struct {
	OrganizaceZkratka string `json:"organizaceZkratka,omitempty"`
	OrganizaceNazev string `json:"organizaceNazev,omitempty"`
	SupportEmail string `json:"supportEmail,omitempty"`
}
