/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetEctsInfoType struct {
	Fakulta string `json:"fakulta"`
	Katedra string `json:"katedra"`
	Zkratka string `json:"zkratka"`
	Rok string `json:"rok"`
	NazevCZ string `json:"nazevCZ"`
	NazevEN string `json:"nazevEN"`
	Akreditace string `json:"akreditace"`
	EctsAkreditace string `json:"ectsAkreditace"`
	EctsZobrazit string `json:"ectsZobrazit"`
	NabizetUPrijezdu string `json:"nabizetUPrijezdu"`
	Kreditu int32 `json:"kreditu"`
	Garanti string `json:"garanti,omitempty"`
	CileCZ string `json:"cileCZ,omitempty"`
	CileEN string `json:"cileEN,omitempty"`
	PredpokladyCZ string `json:"predpokladyCZ,omitempty"`
	PredpokladyEN string `json:"predpokladyEN,omitempty"`
	ZpusobilostiCZ string `json:"zpusobilostiCZ,omitempty"`
	ZpusobilostiEN string `json:"zpusobilostiEN,omitempty"`
	PozadavkyCZ string `json:"pozadavkyCZ,omitempty"`
	PozadavkyEN string `json:"pozadavkyEN,omitempty"`
	PredmetURL string `json:"predmetURL,omitempty"`
	PrehledLatkyCZ string `json:"prehledLatkyCZ,omitempty"`
	PrehledLatkyEN string `json:"prehledLatkyEN,omitempty"`
	MetodyVyucovaciCZ string `json:"metodyVyucovaciCZ,omitempty"`
	MetodyVyucovaciEN string `json:"metodyVyucovaciEN,omitempty"`
	MetodyHodnoticiCZ string `json:"metodyHodnoticiCZ,omitempty"`
	MetodyHodnoticiEN string `json:"metodyHodnoticiEN,omitempty"`
	CasovaNarocnostCZ string `json:"casovaNarocnostCZ,omitempty"`
	CasovaNarocnostEN string `json:"casovaNarocnostEN,omitempty"`
	LiteraturaPocet int32 `json:"literaturaPocet,omitempty"`
}
