/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProgramInfoType struct {
	StprIdno int64 `json:"stprIdno"`
	Nazev string `json:"nazev"`
	NazevCz string `json:"nazevCz,omitempty"`
	NazevAn string `json:"nazevAn,omitempty"`
	Kod string `json:"kod"`
	Titul string `json:"titul,omitempty"`
	TitulZkr string `json:"titulZkr,omitempty"`
	TitulRigo string `json:"titulRigo,omitempty"`
	TitulRigoZkr string `json:"titulRigoZkr,omitempty"`
	Typ string `json:"typ"`
	Forma string `json:"forma"`
	Fakulta string `json:"fakulta"`
	StdDelka float32 `json:"stdDelka"`
	MaxDelka float32 `json:"maxDelka"`
	Kredity int32 `json:"kredity"`
	Vykazovan string `json:"vykazovan"`
	PlatnyOd string `json:"platnyOd,omitempty"`
	NeplatnyOd string `json:"neplatnyOd,omitempty"`
	Cile string `json:"cile,omitempty"`
	Garant string `json:"garant,omitempty"`
	GarantUcitIdno int64 `json:"garantUcitIdno,omitempty"`
	GarantAdministrace string `json:"garantAdministrace,omitempty"`
	GarantAdministraceUcitIdno int64 `json:"garantAdministraceUcitIdno,omitempty"`
	Jazyk string `json:"jazyk,omitempty"`
	Profil string `json:"profil,omitempty"`
	AkreditacePoNovele string `json:"akreditacePoNovele,omitempty"`
	AkreditaceInstitucionalni string `json:"akreditaceInstitucionalni,omitempty"`
	AkreditaceOdDate string `json:"akreditaceOdDate,omitempty"`
	AkreditaceDoDate string `json:"akreditaceDoDate,omitempty"`
	AkreditaceZtracenaOdDate string `json:"akreditaceZtracenaOdDate,omitempty"`
	AkreditovanSeSpecializaci string `json:"akreditovanSeSpecializaci,omitempty"`
	AkreditaceCislo string `json:"akreditaceCislo,omitempty"`
	KodIsced string `json:"kodIsced,omitempty"`
	NavaznostNaDalsiSpCz string `json:"navaznostNaDalsiSpCz,omitempty"`
	NavaznostNaDalsiSpAn string `json:"navaznostNaDalsiSpAn,omitempty"`
	NavaznostNaDalsiSpJ3 string `json:"navaznostNaDalsiSpJ3,omitempty"`
	NavaznostNaDalsiSpJ4 string `json:"navaznostNaDalsiSpJ4,omitempty"`
	ObsahoveZamereniCz string `json:"obsahoveZamereniCz,omitempty"`
	ObsahoveZamereniAn string `json:"obsahoveZamereniAn,omitempty"`
	ObsahoveZamereniJ3 string `json:"obsahoveZamereniJ3,omitempty"`
	ObsahoveZamereniJ4 string `json:"obsahoveZamereniJ4,omitempty"`
	PozadovanaZdrZpusobilostCz string `json:"pozadovanaZdrZpusobilostCz,omitempty"`
	PozadovanaZdrZpusobilostAn string `json:"pozadovanaZdrZpusobilostAn,omitempty"`
	PozadovanaZdrZpusobilostJ3 string `json:"pozadovanaZdrZpusobilostJ3,omitempty"`
	PozadovanaZdrZpusobilostJ4 string `json:"pozadovanaZdrZpusobilostJ4,omitempty"`
	ProfilAbsolventaCz string `json:"profilAbsolventaCz,omitempty"`
	ProfilAbsolventaAn string `json:"profilAbsolventaAn,omitempty"`
	ProfilAbsolventaJ3 string `json:"profilAbsolventaJ3,omitempty"`
	ProfilAbsolventaJ4 string `json:"profilAbsolventaJ4,omitempty"`
	PocetPrijimanych int32 `json:"pocetPrijimanych,omitempty"`
	PocetPrijimanychPoznamka string `json:"pocetPrijimanychPoznamka,omitempty"`
	PozadavkyNaPrijetiCz string `json:"pozadavkyNaPrijetiCz,omitempty"`
	PozadavkyNaPrijetiAn string `json:"pozadavkyNaPrijetiAn,omitempty"`
	PozadavkyNaPrijetiUrl string `json:"pozadavkyNaPrijetiUrl,omitempty"`
	PozadavkyRovnyPristupZdrCz string `json:"pozadavkyRovnyPristupZdrCz,omitempty"`
	PozadavkyRovnyPristupZdrAn string `json:"pozadavkyRovnyPristupZdrAn,omitempty"`
	PozadavkyRovnyPristupZdrJ3 string `json:"pozadavkyRovnyPristupZdrJ3,omitempty"`
	PozadavkyRovnyPristupZdrJ4 string `json:"pozadavkyRovnyPristupZdrJ4,omitempty"`
	PredpokladUplatitelnostiCz string `json:"predpokladUplatitelnostiCz,omitempty"`
	PredpokladUplatitelnostiAn string `json:"predpokladUplatitelnostiAn,omitempty"`
	PredpokladUplatitelnostiJ3 string `json:"predpokladUplatitelnostiJ3,omitempty"`
	PredpokladUplatitelnostiJ4 string `json:"predpokladUplatitelnostiJ4,omitempty"`
	RegulovanePovolaniCz string `json:"regulovanePovolaniCz,omitempty"`
	RegulovanePovolaniAn string `json:"regulovanePovolaniAn,omitempty"`
	RegulovanePovolaniJ3 string `json:"regulovanePovolaniJ3,omitempty"`
	RegulovanePovolaniJ4 string `json:"regulovanePovolaniJ4,omitempty"`
	RegulovanePovolaniUznavaciO string `json:"regulovanePovolaniUznavaciO,omitempty"`
	RegulovanePovolaniDatum string `json:"regulovanePovolaniDatum,omitempty"`
	MoznePracovniPoziceCz string `json:"moznePracovniPoziceCz,omitempty"`
	MoznePracovniPoziceAn string `json:"moznePracovniPoziceAn,omitempty"`
	MoznePracovniPoziceJ3 string `json:"moznePracovniPoziceJ3,omitempty"`
	MoznePracovniPoziceJ4 string `json:"moznePracovniPoziceJ4,omitempty"`
	VyukaZahranicniPredpis string `json:"vyukaZahranicniPredpis,omitempty"`
	VyukaAVCRPracoviste string `json:"vyukaAVCRPracoviste,omitempty"`
	AkreditaceOmezenaDuvod string `json:"akreditaceOmezenaDuvod,omitempty"`
	AkreditaceOmezenaCislo string `json:"akreditaceOmezenaCislo,omitempty"`
	AkreditaceOmezenaOd string `json:"akreditaceOmezenaOd,omitempty"`
	KoefEkonomickeNarocnosti float64 `json:"koefEkonomickeNarocnosti,omitempty"`
	TypickaTemataVskp string `json:"typickaTemataVskp,omitempty"`
	PraktickaVyuka string `json:"praktickaVyuka,omitempty"`
	SpolupraceSPraxi string `json:"spolupraceSPraxi,omitempty"`
	OdbornaPraxe string `json:"odbornaPraxe,omitempty"`
	JointDegrees string `json:"jointDegrees,omitempty"`
	PoznamkaVerejna string `json:"poznamkaVerejna,omitempty"`
	PodminkyPokracovaniStudia string `json:"podminkyPokracovaniStudia,omitempty"`
	NazevProDiplomCz string `json:"nazevProDiplomCz,omitempty"`
	NazevProDiplomAn string `json:"nazevProDiplomAn,omitempty"`
}
