/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlokPredmetu struct {
	BlokIdno int64 `json:"blokIdno"`
	MaxKred int32 `json:"maxKred,omitempty"`
	MinKred int32 `json:"minKred,omitempty"`
	MinPocetPredmetu int32 `json:"minPocetPredmetu,omitempty"`
	Poznamka string `json:"poznamka,omitempty"`
	PredmetovyBlokB bool `json:"predmetovyBlokB"`
	Predmety []PredmetVBloku `json:"predmety,omitempty"`
	Statut string `json:"statut,omitempty"`
}
