/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetKatedryType struct {
	Katedra string `json:"katedra"`
	Zkratka string `json:"zkratka"`
	Rok string `json:"rok"`
	Nazev string `json:"nazev"`
	Semestr string `json:"semestr,omitempty"`
	MaVyuku string `json:"maVyuku,omitempty"`
	VyukaZS string `json:"vyukaZS,omitempty"`
	VyukaLS string `json:"vyukaLS,omitempty"`
	Jazyk1 string `json:"jazyk1,omitempty"`
	Jazyk2 string `json:"jazyk2,omitempty"`
	Jazyk3 string `json:"jazyk3,omitempty"`
	Jazyk4 string `json:"jazyk4,omitempty"`
	NabizetPrijezdyEcts string `json:"nabizetPrijezdyEcts,omitempty"`
	PocetStudentu int32 `json:"pocetStudentu,omitempty"`
	AMax int32 `json:"aMax,omitempty"`
	BMax int32 `json:"bMax,omitempty"`
	CMax int32 `json:"cMax,omitempty"`
	ASkut int32 `json:"aSkut,omitempty"`
	BSkut int32 `json:"bSkut,omitempty"`
	CSkut int32 `json:"cSkut,omitempty"`
}
