/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProgramOblVzdelType struct {
	StprIdno int64 `json:"stprIdno"`
	OblastVzdelavani string `json:"oblastVzdelavani"`
	OblastVzdelavaniText string `json:"oblastVzdelavaniText"`
	TematickeOkruhy string `json:"tematickeOkruhy,omitempty"`
}
