/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OborInfoType struct {
	OborIdno int64 `json:"oborIdno"`
	Nazev string `json:"nazev"`
	NazevCz string `json:"nazevCz,omitempty"`
	NazevAn string `json:"nazevAn,omitempty"`
	CisloOboru string `json:"cisloOboru"`
	CisloSpecializace string `json:"cisloSpecializace"`
	Typ string `json:"typ"`
	Forma string `json:"forma"`
	Jazyk string `json:"jazyk"`
	Fakulta string `json:"fakulta"`
	PlatnyOd string `json:"platnyOd,omitempty"`
	NeplatnyOd string `json:"neplatnyOd,omitempty"`
	KodIsced string `json:"kodIsced"`
	Anotace string `json:"anotace,omitempty"`
	AnotaceCz string `json:"anotaceCz,omitempty"`
	AnotaceAn string `json:"anotaceAn,omitempty"`
	LimitKreditu int32 `json:"limitKreditu,omitempty"`
	PocetEtap int32 `json:"pocetEtap,omitempty"`
	MaxDelka float64 `json:"maxDelka,omitempty"`
	StdDelka float64 `json:"stdDelka,omitempty"`
	StprIdno int64 `json:"stprIdno,omitempty"`
	Zkratka string `json:"zkratka,omitempty"`
	Garant string `json:"garant,omitempty"`
	GarantUcitIdno int64 `json:"garantUcitIdno,omitempty"`
	Garant2 string `json:"garant2,omitempty"`
	Garant2UcitIdno int64 `json:"garant2UcitIdno,omitempty"`
	NazevProgramu string `json:"nazevProgramu,omitempty"`
	KodProgramu string `json:"kodProgramu,omitempty"`
	ProfilProgramu string `json:"profilProgramu,omitempty"`
	ProgramAkreditacePoNovele string `json:"programAkreditacePoNovele,omitempty"`
	ProgramAkreditovanSCislemOboru string `json:"programAkreditovanSCislemOboru,omitempty"`
	VzdelavaciCile string `json:"vzdelavaciCile,omitempty"`
	ProfesniProfilyAbsolventu string `json:"profesniProfilyAbsolventu,omitempty"`
	KvalifikacniPozadavky string `json:"kvalifikacniPozadavky,omitempty"`
	PozadavkyNaPrijetiCz string `json:"pozadavkyNaPrijetiCz,omitempty"`
	PozadavkyNaPrijetiAn string `json:"pozadavkyNaPrijetiAn,omitempty"`
	PozadavkyNaPrijetiUrl string `json:"pozadavkyNaPrijetiUrl,omitempty"`
	PocetPrijimanych int32 `json:"pocetPrijimanych,omitempty"`
	PocetPrijimanychPoznamka string `json:"pocetPrijimanychPoznamka,omitempty"`
	PozadovanaZdrZpusobilostCz string `json:"pozadovanaZdrZpusobilostCz,omitempty"`
	PozadovanaZdrZpusobilostAn string `json:"pozadovanaZdrZpusobilostAn,omitempty"`
	ProfilAbsolventaCz string `json:"profilAbsolventaCz,omitempty"`
	ProfilAbsolventaAn string `json:"profilAbsolventaAn,omitempty"`
	PredpokladUplatitelnostiCz string `json:"predpokladUplatitelnostiCz,omitempty"`
	PredpokladUplatitelnostiAn string `json:"predpokladUplatitelnostiAn,omitempty"`
	MoznePracovniPoziceCz string `json:"moznePracovniPoziceCz,omitempty"`
	MoznePracovniPoziceAn string `json:"moznePracovniPoziceAn,omitempty"`
	RegulovanePovolaniCz string `json:"regulovanePovolaniCz,omitempty"`
	RegulovanePovolaniAn string `json:"regulovanePovolaniAn,omitempty"`
	RegulovanePovolaniUznavaciO string `json:"regulovanePovolaniUznavaciO,omitempty"`
	PoznamkaVerejna string `json:"poznamkaVerejna,omitempty"`
	MarketingDoplnkoveInf string `json:"marketingDoplnkoveInf,omitempty"`
	MarketingFormaStudia string `json:"marketingFormaStudia,omitempty"`
	MarketingPopis string `json:"marketingPopis,omitempty"`
	MarketingPoznamka string `json:"marketingPoznamka,omitempty"`
	MarketingStudiumInf string `json:"marketingStudiumInf,omitempty"`
	MarketingUplatneni string `json:"marketingUplatneni,omitempty"`
	NazevProDiplomCz string `json:"nazevProDiplomCz,omitempty"`
	NazevProDiplomAn string `json:"nazevProDiplomAn,omitempty"`
}
