/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetInfoType struct {
	Katedra string `json:"katedra"`
	Zkratka string `json:"zkratka"`
	Rok string `json:"rok"`
	Nazev string `json:"nazev"`
	NazevDlouhy string `json:"nazevDlouhy"`
	MaVyuku string `json:"maVyuku,omitempty"`
	VyukaZS string `json:"vyukaZS"`
	VyukaLS string `json:"vyukaLS"`
	JakCastoJeNabizen string `json:"jakCastoJeNabizen"`
	JakCastoJeNabizenUpresneni string `json:"jakCastoJeNabizenUpresneni"`
	Kreditu int32 `json:"kreditu"`
	ViceZapis string `json:"viceZapis,omitempty"`
	MinObsazeni int32 `json:"minObsazeni,omitempty"`
	Garanti string `json:"garanti,omitempty"`
	GarantiSPodily string `json:"garantiSPodily,omitempty"`
	GarantiUcitIdno string `json:"garantiUcitIdno,omitempty"`
	Prednasejici string `json:"prednasejici,omitempty"`
	PrednasejiciSPodily string `json:"prednasejiciSPodily,omitempty"`
	PrednasejiciUcitIdno string `json:"prednasejiciUcitIdno,omitempty"`
	Cvicici string `json:"cvicici,omitempty"`
	CviciciSPodily string `json:"cviciciSPodily,omitempty"`
	CviciciUcitIdno string `json:"cviciciUcitIdno,omitempty"`
	Seminarici string `json:"seminarici,omitempty"`
	SeminariciSPodily string `json:"seminariciSPodily,omitempty"`
	SeminariciUcitIdno string `json:"seminariciUcitIdno,omitempty"`
	SchvalujiciUznani string `json:"schvalujiciUznani,omitempty"`
	SchvalujiciUznaniUcitIdno string `json:"schvalujiciUznaniUcitIdno,omitempty"`
	Examinatori string `json:"examinatori,omitempty"`
	ExaminatoriUcitIdno string `json:"examinatoriUcitIdno,omitempty"`
	PodminujiciPredmety string `json:"podminujiciPredmety,omitempty"`
	VylucujiciPredmety string `json:"vylucujiciPredmety,omitempty"`
	PodminujePredmety string `json:"podminujePredmety,omitempty"`
	Literatura string `json:"literatura"`
	NahrazPredmety string `json:"nahrazPredmety,omitempty"`
	MetodyVyucovaci string `json:"metodyVyucovaci,omitempty"`
	MetodyHodnotici string `json:"metodyHodnotici,omitempty"`
	Akreditovan string `json:"akreditovan"`
	JednotekPrednasek int32 `json:"jednotekPrednasek"`
	JednotkaPrednasky string `json:"jednotkaPrednasky"`
	JednotekCviceni int32 `json:"jednotekCviceni"`
	JednotkaCviceni string `json:"jednotkaCviceni"`
	JednotekSeminare int32 `json:"jednotekSeminare"`
	JednotkaSeminare string `json:"jednotkaSeminare"`
	Anotace string `json:"anotace,omitempty"`
	TypZkousky string `json:"typZkousky"`
	MaZapocetPredZk string `json:"maZapocetPredZk"`
	FormaZkousky string `json:"formaZkousky"`
	Pozadavky string `json:"pozadavky,omitempty"`
	PrehledLatky string `json:"prehledLatky,omitempty"`
	Predpoklady string `json:"predpoklady,omitempty"`
	ZiskaneZpusobilosti string `json:"ziskaneZpusobilosti,omitempty"`
	CasovaNarocnost string `json:"casovaNarocnost,omitempty"`
	PredmetUrl string `json:"predmetUrl,omitempty"`
	VyucovaciJazyky string `json:"vyucovaciJazyky,omitempty"`
	Poznamka string `json:"poznamka,omitempty"`
	EctsZobrazit string `json:"ectsZobrazit,omitempty"`
	EctsAkreditace string `json:"ectsAkreditace,omitempty"`
	EctsNabizetUPrijezdu string `json:"ectsNabizetUPrijezdu,omitempty"`
	PoznamkaVerejna string `json:"poznamkaVerejna,omitempty"`
	SkupinaAkreditace string `json:"skupinaAkreditace,omitempty"`
	SkupinaAkreditaceKey string `json:"skupinaAkreditaceKey,omitempty"`
	ZarazenDoPrezencnihoStudia string `json:"zarazenDoPrezencnihoStudia,omitempty"`
	ZarazenDoKombinovanehoStudia string `json:"zarazenDoKombinovanehoStudia,omitempty"`
	StudijniOpory string `json:"studijniOpory,omitempty"`
	PraxePocetDnu string `json:"praxePocetDnu,omitempty"`
	UrovenNastavena string `json:"urovenNastavena,omitempty"`
	UrovenVypoctena string `json:"urovenVypoctena,omitempty"`
	AutomatickyUznavatZppZk string `json:"automatickyUznavatZppZk,omitempty"`
	HodZaSemKombForma string `json:"hodZaSemKombForma,omitempty"`
}
