/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NasazeniAplikaceType struct {
	NazevAplikace string `json:"nazevAplikace,omitempty"`
	NazevSkoly string `json:"nazevSkoly,omitempty"`
	CelyNazevSkoly string `json:"celyNazevSkoly,omitempty"`
	ZkratkaServeru string `json:"zkratkaServeru,omitempty"`
	ProvozniServer string `json:"provozniServer,omitempty"`
	PristupnyBezOmezeni string `json:"pristupnyBezOmezeni,omitempty"`
	Url string `json:"url,omitempty"`
}
