/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VspStudentType struct {
	Email string `json:"email,omitempty"`
	Fakulta string `json:"fakulta,omitempty"`
	Forma string `json:"forma,omitempty"`
	KredityAbsolvovaneNormalniPredmetCelkem float64 `json:"kredityAbsolvovaneNormalniPredmetCelkem"`
	KredityNutnoZiskatProgram int32 `json:"kredityNutnoZiskatProgram"`
	KredityUznaneCelkem float64 `json:"kredityUznaneCelkem"`
	KredityZiskaneCelkem float64 `json:"kredityZiskaneCelkem"`
	OsCislo string `json:"osCislo,omitempty"`
	OsobIdno int64 `json:"osobIdno"`
	PredmetyOsvobozene []PredmetStudentOsvobozen `json:"predmetyOsvobozene,omitempty"`
	RokyStudia []StudentVRoce `json:"rokyStudia,omitempty"`
	StprIdno int64 `json:"stprIdno"`
	Typ string `json:"typ,omitempty"`
}
