/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SegmentInfoType struct {
	SespIdno int64 `json:"sespIdno"`
	Nazev string `json:"nazev"`
	NazevModulu string `json:"nazevModulu,omitempty"`
	Zkratka string `json:"zkratka,omitempty"`
	RokPlatnosti string `json:"rokPlatnosti"`
	MinCrdBBloku int32 `json:"minCrdBBloku,omitempty"`
	MinPocetAbsBBloku int32 `json:"minPocetAbsBBloku,omitempty"`
}
