/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VspStudijniPlanType struct {
	Kreditne bool `json:"kreditne"`
	ModularniPlan bool `json:"modularniPlan"`
	OborIdno int64 `json:"oborIdno"`
	OmezeniZapisu string `json:"omezeniZapisu,omitempty"`
	PocetSemestru int32 `json:"pocetSemestru"`
	PopisPlanuUrl string `json:"popisPlanuUrl,omitempty"`
	RokPlatnosti string `json:"rokPlatnosti,omitempty"`
	SkupinySegmentu []SkupinaSegmentu `json:"skupinySegmentu,omitempty"`
	StplIdno int64 `json:"stplIdno"`
	Verze string `json:"verze,omitempty"`
}
