/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StagUserListV2Type struct {
	Jmeno string `json:"jmeno,omitempty"`
	Prijmeni string `json:"prijmeni,omitempty"`
	TitulPred string `json:"titulPred,omitempty"`
	TitulZa string `json:"titulZa,omitempty"`
	Email string `json:"email,omitempty"`
	StagUserInfo []StagUserType `json:"stagUserInfo,omitempty"`
}
