/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UcitelType struct {
	UcitIdno int64 `json:"ucitIdno"`
	Jmeno string `json:"jmeno"`
	Prijmeni string `json:"prijmeni"`
	TitulPred string `json:"titulPred,omitempty"`
	TitulZa string `json:"titulZa,omitempty"`
	Platnost string `json:"platnost"`
	Zamestnanec string `json:"zamestnanec"`
}
