/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetVBloku struct {
	DoporucenyRocnik int32 `json:"doporucenyRocnik,omitempty"`
	DoporucenySemestr string `json:"doporucenySemestr,omitempty"`
	Id int64 `json:"id"`
	Kredity int32 `json:"kredity"`
	Predmet *PredmetVarianta `json:"predmet,omitempty"`
	VyznamPredmetu string `json:"vyznamPredmetu,omitempty"`
}
