/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StagUserRoleType struct {
	Fakulta string `json:"fakulta,omitempty"`
	Katedra string `json:"katedra,omitempty"`
	IdRole string `json:"idRole,omitempty"`
	NazevRole string `json:"nazevRole,omitempty"`
	UcitIdno int64 `json:"ucitIdno,omitempty"`
	StagUserName string `json:"stagUserName,omitempty"`
	Osoba string `json:"osoba,omitempty"`
	EvaluacniRole string `json:"evaluacniRole,omitempty"`
}
