/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PracovisteForEditType struct {
	CisloPracoviste string `json:"cisloPracoviste,omitempty"`
	CisloPracovisteInterni string `json:"cisloPracovisteInterni,omitempty"`
	Zkratka string `json:"zkratka"`
	Nazev string `json:"nazev,omitempty"`
	Nazev2Pad string `json:"nazev2Pad,omitempty"`
	Nazev3Pad string `json:"nazev3Pad,omitempty"`
	AnNazev string `json:"anNazev,omitempty"`
	NadrazenePracoviste string `json:"nadrazenePracoviste,omitempty"`
	TypPracoviste string `json:"typPracoviste,omitempty"`
	PlatnostOd string `json:"platnostOd,omitempty"`
	PlatnostDo string `json:"platnostDo,omitempty"`
	TypVedouciho string `json:"typVedouciho,omitempty"`
	VedouciUcitIdno int64 `json:"vedouciUcitIdno,omitempty"`
	Url string `json:"url,omitempty"`
	Identifikator string `json:"identifikator,omitempty"`
}
