/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetVarianta struct {
	DoporucenePredmety []PredmetDoporuceny `json:"doporucenePredmety,omitempty"`
	Kredity int32 `json:"kredity"`
	MaVyuku bool `json:"maVyuku"`
	NahrazovanePredmety []PredmetHlavickaKey `json:"nahrazovanePredmety,omitempty"`
	PodminujiciPredmety []PredmetPodminujici `json:"podminujiciPredmety,omitempty"`
	PracZkr string `json:"pracZkr,omitempty"`
	RokVarianty string `json:"rokVarianty,omitempty"`
	Rozsah string `json:"rozsah,omitempty"`
	Statnice bool `json:"statnice"`
	TypZk string `json:"typZk,omitempty"`
	Vicezapis bool `json:"vicezapis"`
	VyloucenePredmety []PredmetHlavickaKey `json:"vyloucenePredmety,omitempty"`
	VyukaLS bool `json:"vyukaLS"`
	VyukaZS bool `json:"vyukaZS"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
}
