/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetStudentaType struct {
	Zkratka string `json:"zkratka"`
	Nazev string `json:"nazev"`
	Katedra string `json:"katedra"`
	Rok string `json:"rok"`
	Kredity int32 `json:"kredity"`
	Uznano string `json:"uznano,omitempty"`
	Statut string `json:"statut,omitempty"`
}
