/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PredmetAkreditaceEctsType struct {
	AnCasNarocnost string `json:"anCasNarocnost,omitempty"`
	AnCasNarocnostAkred string `json:"anCasNarocnostAkred,omitempty"`
	AnCile string `json:"anCile,omitempty"`
	AnCileAkred string `json:"anCileAkred,omitempty"`
	AnHodnMetody string `json:"anHodnMetody,omitempty"`
	AnHodnMetodyAkred string `json:"anHodnMetodyAkred,omitempty"`
	AnJakCastoJeNabizen string `json:"anJakCastoJeNabizen,omitempty"`
	AnJakCastoJeNabizenAkred string `json:"anJakCastoJeNabizenAkred,omitempty"`
	AnNazev string `json:"anNazev,omitempty"`
	AnNazevAkred string `json:"anNazevAkred,omitempty"`
	AnNazevDlouhy string `json:"anNazevDlouhy,omitempty"`
	AnNazevDlouhyAkred string `json:"anNazevDlouhyAkred,omitempty"`
	AnPozadavky string `json:"anPozadavky,omitempty"`
	AnPozadavkyAkred string `json:"anPozadavkyAkred,omitempty"`
	AnPredpoklady string `json:"anPredpoklady,omitempty"`
	AnPredpokladyAkred string `json:"anPredpokladyAkred,omitempty"`
	AnPrehledLatky string `json:"anPrehledLatky,omitempty"`
	AnPrehledLatkyAkred string `json:"anPrehledLatkyAkred,omitempty"`
	AnVyuc string `json:"anVyuc,omitempty"`
	AnVyucAkred string `json:"anVyucAkred,omitempty"`
	AnVyucMetody string `json:"anVyucMetody,omitempty"`
	AnVyucMetodyAkred string `json:"anVyucMetodyAkred,omitempty"`
	Crd string `json:"crd,omitempty"`
	CrdAkred string `json:"crdAkred,omitempty"`
	CzCasNarocnost string `json:"czCasNarocnost,omitempty"`
	CzCasNarocnostAkred string `json:"czCasNarocnostAkred,omitempty"`
	CzCile string `json:"czCile,omitempty"`
	CzCileAkred string `json:"czCileAkred,omitempty"`
	CzHodnMetody string `json:"czHodnMetody,omitempty"`
	CzHodnMetodyAkred string `json:"czHodnMetodyAkred,omitempty"`
	CzJakCastoJeNabizen string `json:"czJakCastoJeNabizen,omitempty"`
	CzJakCastoJeNabizenAkred string `json:"czJakCastoJeNabizenAkred,omitempty"`
	CzNazev string `json:"czNazev,omitempty"`
	CzNazevAkred string `json:"czNazevAkred,omitempty"`
	CzNazevDlouhy string `json:"czNazevDlouhy,omitempty"`
	CzNazevDlouhyAkred string `json:"czNazevDlouhyAkred,omitempty"`
	CzPozadavky string `json:"czPozadavky,omitempty"`
	CzPozadavkyAkred string `json:"czPozadavkyAkred,omitempty"`
	CzPredpoklady string `json:"czPredpoklady,omitempty"`
	CzPredpokladyAkred string `json:"czPredpokladyAkred,omitempty"`
	CzPrehledLatky string `json:"czPrehledLatky,omitempty"`
	CzPrehledLatkyAkred string `json:"czPrehledLatkyAkred,omitempty"`
	CzVyuc string `json:"czVyuc,omitempty"`
	CzVyucAkred string `json:"czVyucAkred,omitempty"`
	CzVyucMetody string `json:"czVyucMetody,omitempty"`
	CzVyucMetodyAkred string `json:"czVyucMetodyAkred,omitempty"`
	DatumPosledniAkred string `json:"datumPosledniAkred,omitempty"`
	ExportColorsInfo string `json:"exportColorsInfo,omitempty"`
	Fakulta string `json:"fakulta,omitempty"`
	HodZaSemKombForma string `json:"hodZaSemKombForma,omitempty"`
	HodZaSemKombFormaAkred string `json:"hodZaSemKombFormaAkred,omitempty"`
	J3Vyuc string `json:"j3Vyuc,omitempty"`
	J3VyucAkred string `json:"j3VyucAkred,omitempty"`
	J4Vyuc string `json:"j4Vyuc,omitempty"`
	J4VyucAkred string `json:"j4VyucAkred,omitempty"`
	JednotekCv string `json:"jednotekCv,omitempty"`
	JednotekCvAkred string `json:"jednotekCvAkred,omitempty"`
	JednotekPr string `json:"jednotekPr,omitempty"`
	JednotekPrAkred string `json:"jednotekPrAkred,omitempty"`
	JednotekSem string `json:"jednotekSem,omitempty"`
	JednotekSemAkred string `json:"jednotekSemAkred,omitempty"`
	Literatura string `json:"literatura,omitempty"`
	LiteraturaAkred string `json:"literaturaAkred,omitempty"`
	PodminujiciPredm string `json:"podminujiciPredm,omitempty"`
	PodminujiciPredmAkred string `json:"podminujiciPredmAkred,omitempty"`
	PracZkr string `json:"pracZkr,omitempty"`
	PracovniStaze string `json:"pracovniStaze,omitempty"`
	PracovniStazeAkred string `json:"pracovniStazeAkred,omitempty"`
	StavEctsAkreditace string `json:"stavEctsAkreditace,omitempty"`
	Ucitele string `json:"ucitele,omitempty"`
	UciteleAkred string `json:"uciteleAkred,omitempty"`
	UrovenNastavena string `json:"urovenNastavena,omitempty"`
	UrovenNastavenaAkred string `json:"urovenNastavenaAkred,omitempty"`
	UrovenVypoctena string `json:"urovenVypoctena,omitempty"`
	UrovenVypoctenaAkred string `json:"urovenVypoctenaAkred,omitempty"`
	ZkrPredm string `json:"zkrPredm,omitempty"`
	ZpusobVyuky string `json:"zpusobVyuky,omitempty"`
	ZpusobVyukyAkred string `json:"zpusobVyukyAkred,omitempty"`
}
