/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OborPredmetuType struct {
	StprIdno int64 `json:"stprIdno"`
	NazevProgramu string `json:"nazevProgramu"`
	KodProgramu string `json:"kodProgramu"`
	FormaProgramu string `json:"formaProgramu"`
	TypProgramu string `json:"typProgramu"`
	FakultaProgramu string `json:"fakultaProgramu"`
	OborIdno int64 `json:"oborIdno"`
	NazevOboru string `json:"nazevOboru"`
	CisloOboru string `json:"cisloOboru"`
	CisloSpecializace string `json:"cisloSpecializace"`
	StplIdno int64 `json:"stplIdno"`
	EtapaPlanu string `json:"etapaPlanu,omitempty"`
	RokPlatnostiPlanu string `json:"rokPlatnostiPlanu"`
	NazevSegmentu string `json:"nazevSegmentu,omitempty"`
	BlokIdno int64 `json:"blokIdno"`
	NazevBloku string `json:"nazevBloku,omitempty"`
	StatutBloku string `json:"statutBloku"`
	DoporucenyRocnik string `json:"doporucenyRocnik,omitempty"`
	DoporucenySemestr string `json:"doporucenySemestr,omitempty"`
	VyznamPredmetu string `json:"vyznamPredmetu,omitempty"`
}
