/*
 * IS/STAG Web Services API
 *
 * Automaticky generovaná OpenAPI specifikace z WADL souborů pro webové služby IS/STAG.
 *
 * API version: 2.0.0
 * Contact: podpora@service.zcu.cz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StudentNaOboruVRoce struct {
	KredityAbsolvovaneNormalniPredmety float64 `json:"kredityAbsolvovaneNormalniPredmety"`
	KredityAbsolvovaneUznanePredmety float64 `json:"kredityAbsolvovaneUznanePredmety"`
	KredityNutnoZiskatObor int32 `json:"kredityNutnoZiskatObor"`
	KredityPlan float64 `json:"kredityPlan"`
	KredityUznaneCelkem float64 `json:"kredityUznaneCelkem"`
	KredityUznaneRucne float64 `json:"kredityUznaneRucne"`
	KredityZiskaneCelkem float64 `json:"kredityZiskaneCelkem"`
	OborIdno int64 `json:"oborIdno"`
	OrIdno int64 `json:"orIdno,omitempty"`
	Predmety []PredmetStudenta `json:"predmety,omitempty"`
	StplIdno int64 `json:"stplIdno"`
}
